window.ENV_COURSE_CONFIG = {
  missionStorageKey: "environnements-connectes-mission-v1",
  release: { releasedThrough: 1 },
  course: {
    code: "Environnements connectés et données",
    title: "Mission Vallée des Aldudes",
    subtitle: "Cinq rendez-vous dans la même vallée : observer, connecter, représenter, décider puis éprouver le système dans la durée."
  },
  sessions: [
    {id:1,number:"01",kicker:"OBSERVER",episode:"ÉPISODE 1",timecode:"LUNDI · 08:42",title:"Que faut-il vraiment connaître ?",question:"Avant de choisir des capteurs ou un réseau, quelles informations peuvent réellement aider à décider ?",story:"Vous partez du terrain et de quelques situations concrètes. Vous choisissez ce qui mérite d’être observé, puis vous rendez visibles les limites de cette première vision.",inherits:"Dossier terrain initial",deliverable:"Stratégie d’observation v2",objectives:["besoin → observation","sources & contexte","qualité & limites"],storageKey:"environnements-connectes-session1-v9",progressKind:"activity-frontier",progressLabels:["Prioriser","Décider","Observer","Comparer","Interpréter","Contextualiser","Choisir","Tester l’usage","Composer","Réviser"]},
    {id:2,number:"02",kicker:"CONNECTER",episode:"ÉPISODE 2",timecode:"MARDI · 07:56",title:"Comment l’information arrive-t-elle ?",question:"Vos sources existent maintenant sur le papier. Comment leurs données rejoignent-elles réellement l’endroit où elles seront utiles ?",story:"Vous repartez des sources, fréquences et limites retenues en S1. Cette fois, il faut tracer le chemin des données et décider ce qui se passe lorsque la liaison n’est pas permanente.",inherits:"Sources + fréquences + limites de S1",deliverable:"Architecture de collecte v2",objectives:["chaîne de collecte","contraintes de communication","local · edge · cloud"]},
    {id:3,number:"03",kicker:"REPRÉSENTER",episode:"ÉPISODE 3",timecode:"MERCREDI · 10:21",title:"Que signifie vraiment « état actuel » ?",question:"Les flux de S2 arrivent, mais pas tous au même instant ni avec le même contexte. Peut-on les afficher comme un seul état du territoire ?",story:"Vous repartez des chemins, délais et traitements choisis en S2. Le problème n’est plus de faire arriver les données, mais de savoir ce qu’elles décrivent réellement ensemble.",inherits:"Flux + délais + traitements de S2",deliverable:"État numérique qualifié",objectives:["temps & espace","interopérabilité","fusion & incertitude"]},
    {id:4,number:"04",kicker:"DÉCIDER",episode:"ÉPISODE 4",timecode:"JEUDI · 14:08",title:"Que peut-on faire de cet état ?",question:"Votre représentation de S3 est enfin explicite. Quand suffit-il d’informer, et quand peut-on recommander ou déclencher une action ?",story:"Vous repartez d’un état dont les limites sont visibles. Il faut maintenant distinguer alerte, prédiction, décision et automatisation — et savoir qui reste responsable.",inherits:"État + confiance + incertitude de S3",deliverable:"Boucle de décision v2",objectives:["détection & prédiction","human-in-the-loop","jumeau numérique"]},
    {id:5,number:"05",kicker:"ÉPROUVER",episode:"ÉPISODE 5",timecode:"SIX MOIS PLUS TARD",title:"Le système mérite-t-il de durer ?",question:"La chaîne complète fonctionne. Que reste-t-il quand arrivent maintenance, sécurité, coût, obsolescence et pannes ?",story:"Vous repartez de tout le système construit en S1–S4. Six mois plus tard, une technologie de plus ne résoudra pas à elle seule les problèmes de maintenance, de sécurité, de coût, d’obsolescence ou de panne. Vous devez défendre ce qui mérite réellement de rester.",inherits:"Système complet S1–S4",deliverable:"Architecture finale défendable",objectives:["résilience","maintenance & sécurité","coût & sobriété"]}
  ]
};
